export interface AppConfig {
  APP_NAME: string
  DATABASE_URL: string
  PASSWORD_HASH_SALT_OR_ROUNDS: string
  OTP_SECRET_LENGTH: string;
  OTP_LENGTH: string;
  OTP_TTL_IN_SECONDS: string;
  OTP_TIME_WINDOW: string;
  OTP_ENCODING: string;
  OTP_AUTH_TTL_IN_SECONDS: string
  OTP_AUTH_TIME_WINDOW: string
  JWT_SECRET: string
  JWT_TEMP_ACCESS_TOKEN_TTL_IN_SECONDS: string
  JWT_ACCESS_TOKEN_TTL_IN_SECONDS: string
  JWT_REFRESH_TOKEN_TTL_IN_SECONDS: string
  MAIL_HOST: string
  MAIL_USERNAME: string
  MAIL_PASSWORD: string
  MAIL_PORT: string
  MAIL_SECURE: 'true' | 'false'
  MAIL_REQUIRE_TLS: 'true' | 'false'
  MAIL_SENDER: string
  PAYMENT_REWARD_SENDER_KEY: string
  PAYMENT_REWARD_SENDER_ADDRESS: string
  AD_VIEW_REWARD_SENDER_KEY: string
  AD_VIEW_REWARD_SENDER_ADDRESS: string
  SOLUTION_REWARD_SENDER_KEY: string
  SOLUTION_REWARD_SENDER_ADDRESS: string
  ENTRY_REWARD_SENDER_KEY: string
  ENTRY_REWARD_SENDER_ADDRESS: string
}
